spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = ""
name = "http-crud-js"
version = "0.1.0"

[variables]
db_connection_string = { required = true }

[[trigger.http]]
route = "/..."
component = "crud-api"

[component.crud-api]
source = "dist/crud-api.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["postgres://localhost"]

[component.crud-api.variables]
db_connection_string = "{{ db_connection_string }}"

[component.crud-api.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.js"]
