version: "3.9"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: spring_rs_gerust
      POSTGRES_USER: spring_rs_gerust
      POSTGRES_DB: spring_rs_gerust
    ports:
      - 5432:5432
  postgres_test:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: spring_rs_gerust_test
      POSTGRES_USER: spring_rs_gerust_test
      POSTGRES_DB: spring_rs_gerust_test
    ports:
      - 5433:5432
