# Copyright 2025 HM Revenue & Customs
#

include "backend.conf"

# This is the main configuration file for the application.
# ~~~~~

appName = crs-fatca-reporting

# Default http client
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"

# Play Modules
play.modules.enabled += "uk.gov.hmrc.mongo.play.PlayMongoModule"

play.modules.enabled += "config.Module"

# The application languages
# ~~~~~
play.i18n.langs = ["en"]

# Router
# ~~~~~
# Define the Router object to use for this application.
# This router will be looked up first when the application is starting up,
# so make sure this is the entry point.
# Furthermore, it's assumed your route file is named properly.
# So for an application router like `my.application.Router`,
# you may need to define a router file `conf/my.application.routes`.
# Default to Routes in the root package (and conf/routes)
# !!!WARNING!!! DO NOT CHANGE THIS ROUTER
play.http.router = prod.Routes

# Controller
# ~~~~~
# By default all controllers will have authorisation, logging and
# auditing (transaction monitoring) enabled.
# The below controllers are the default exceptions to this rule.

controllers {
}

# Microservice specific config

mongodb {
  uri = "mongodb://localhost:27017/crs-fatca-reporting"
  timeToLiveInSeconds = 900
  submission.timeToLiveInDays = 28
}

microservice {
  services {
    auth {
      host = localhost
      port = 8500
    }
    crs-fatca-fi-management {
      protocol = http
      host = localhost
      port = 10034
    }

    view-elections-details {
          host = localhost
          port = 10035
          protocol = http
          bearer-token = ""
          environment = ""
     }

     submit-elections-details {
       host = localhost
       port = 10035
       protocol = http
       bearer-token = ""
       environment = ""
     }

     sdes {
       host = localhost
       port = 9191
       protocol = http
     }

     crs-fatca-registration {
        host = localhost
        port = 10031
        protocol = http
        base-path = "/crs-fatca-registration"
     }

     crs-submission {
       host = localhost
       port = 10023
       protocol = http
       bearer-token = ""
       environment = ""
     }

     fatca-submission {
       host = localhost
       port = 10023
       protocol = http
       bearer-token = ""
       environment = ""
     }

     crs-eis-callback {
       bearer-token = "test-token"
       wait-time = 10
     }
       fatca-eis-callback {
       bearer-token = "test-token"
       wait-time = 10
     }
  }
}

xsd-files {
  fileUpload_FATCA_XSDFile = "/xsd/fatca/FatcaXML_v2.0.xsd"
  fileUpload_CRS_XSDFile = "/xsd/crs/CrsXML_v3.0.xsd"
  eis_CRS_FileUploadResponse_XSDFile = "/xsd/crs/EIS_File_Upload_Response.xsd"
  eis_FATCA_FileUploadResponse_XSDFile = "/xsd/fatca/EIS_File_Upload_Response.xsd"
}

reportingPeriod {
    earliestDate = "2014-12-31"
}

sdes {
  location = "sdes-stub"
  client-id = "client-id"
  information-type = "crs-fatca-report"
  recipient-or-sender = "crs-fatca-reporting"
  checksum-algorithm = "SHA-256"
}
